# Generated by Django 2.0.13 on 2019-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
